"""
Synthesizer stage for Promptimal v2 - Final prompt synthesis.
Combines best elements from ranked variations with rubric compliance.

Key differences from v1:
- Receives rubric data (was generated by CriticFirst)
- Uses rankings instead of detailed issues list
- More focused synthesis with rubric-guided improvements
"""

import json
from typing import Dict, Any, Optional

from config import GEMINI_FAST
from schemas import (
    SynthesizerOutput,
    ExpansionsOutput,
    RankingsOutput,
    RubricOutput,
    DiscernOutput,
    minify_json,
    validate_stage_output
)
from llm_wrapper import call_llm, parse_json_response
from utils import log_event


# ============================================================================
# SYNTHESIZER PROMPT TEMPLATE (v2 - rubric-aware)
# ============================================================================
SYNTHESIZER_PROMPT = """You are an expert prompt synthesizer. Create the FINAL optimized prompt.

ORIGINAL IDEA:
{idea}

DISCERNMENT (Task Analysis):
{discern_json}

RUBRIC (Quality Criteria):
{rubric_json}

RANKED VARIATIONS (Best → Worst):
{ranked_variations}

YOUR TASK:
1. Start from the BEST ranked variation
2. Incorporate superior elements from lower-ranked variations
3. Ensure ALL rubric criteria are satisfied
4. Avoid ALL red flags listed in the rubric
5. Include explicit anti-hallucination guardrails

OUTPUT FORMAT - respond with ONLY valid JSON:
{{
  "final_prompt": "<the complete optimized prompt>",
  "synthesis_notes": "<explain your synthesis decisions>",
  "rubric_compliance": {{"<criterion>": "<how addressed>", ...}},
  "confidence": <0.0-1.0>
}}

QUALITY REQUIREMENTS:
- Complete, standalone prompt (no placeholders)
- Clear structure with sections if needed
- Explicit constraints to prevent hallucination
- Actionable and specific instructions"""


def synthesize_final(
    idea: str,
    discern: DiscernOutput,
    rubric: RubricOutput,
    expansions: ExpansionsOutput,
    rankings: RankingsOutput,
    max_tokens: int = 800
) -> SynthesizerOutput:
    """
    Synthesize final prompt from ranked variations.
    
    Args:
        idea: Original user idea
        discern: Task analysis from Discerner
        rubric: Quality criteria from CriticFirst
        expansions: Three variations from Expander
        rankings: Rankings from Ranker
        max_tokens: Max response tokens
    
    Returns:
        Validated SynthesizerOutput with final prompt
    """
    log_event("stage.synthesizer.start", {})
    
    # Build ranked variations display
    rank_order = get_ranked_variations(expansions, rankings)
    
    prompt = SYNTHESIZER_PROMPT.format(
        idea=idea[:500],  # Truncate very long ideas
        discern_json=minify_json(discern.model_dump()),
        rubric_json=minify_json({
            "rubric": rubric.rubric,
            "checklist": rubric.checklist[:6],  # Top 6 items
            "red_flags": rubric.red_flags
        }),
        ranked_variations=rank_order
    )
    
    response = call_llm(
        model=GEMINI_FAST,
        prompt=prompt,
        max_tokens=max_tokens,
        enforce_json=True,
        temperature=0.0
    )
    
    raw_output = parse_json_response(response["content"])
    validated = validate_stage_output(raw_output, SynthesizerOutput)
    
    log_event("stage.synthesizer.success", {
        "confidence": validated.confidence,
        "prompt_length": len(validated.final_prompt)
    })
    
    return validated


def get_ranked_variations(
    expansions: ExpansionsOutput,
    rankings: RankingsOutput
) -> str:
    """
    Format variations in ranked order for synthesis.
    
    Returns:
        Formatted string with variations ordered best→worst
    """
    variations = {
        'A': expansions.A,
        'B': expansions.B,
        'C': expansions.C
    }
    
    ranks = {
        'A': rankings.A.rank,
        'B': rankings.B.rank,
        'C': rankings.C.rank
    }
    
    # Sort by rank (1=best)
    ordered = sorted(ranks.items(), key=lambda x: x[1])
    
    result = []
    for key, rank in ordered:
        var = variations[key]
        result.append(f"""
--- RANK {rank} (Variation {key}) ---
PROMPT:
{var.prompt}

Notes: {var.notes}
Checklist Score: {var.checklist_score}
---
""")
    
    return "\n".join(result)


def build_output_json(
    idea: str,
    discern: DiscernOutput,
    rubric: RubricOutput,
    expansions: ExpansionsOutput,
    rankings: RankingsOutput,
    final: SynthesizerOutput
) -> Dict[str, Any]:
    """
    Build complete output JSON matching example_output.json format.
    
    Args:
        All stage outputs
    
    Returns:
        Complete JSON structure for final output
    """
    return {
        "original_idea": idea,
        "task_analysis": discern.model_dump(),
        "rubric": {
            "criteria": rubric.rubric,
            "checklist": rubric.checklist,
            "red_flags": rubric.red_flags
        },
        "variations": {
            "A": {
                "prompt": expansions.A.prompt,
                "notes": expansions.A.notes,
                "checklist_score": expansions.A.checklist_score,
                "rank": rankings.A.rank,
                "score": rankings.A.score
            },
            "B": {
                "prompt": expansions.B.prompt,
                "notes": expansions.B.notes,
                "checklist_score": expansions.B.checklist_score,
                "rank": rankings.B.rank,
                "score": rankings.B.score
            },
            "C": {
                "prompt": expansions.C.prompt,
                "notes": expansions.C.notes,
                "checklist_score": expansions.C.checklist_score,
                "rank": rankings.C.rank,
                "score": rankings.C.score
            }
        },
        "final_synthesis": {
            "prompt": final.final_prompt,
            "notes": final.synthesis_notes,
            "rubric_compliance": final.rubric_compliance,
            "confidence": final.confidence
        }
    }
